### ISSUE TITLE
build 38 or 37

### ISSUE THREAD

**Issue by kevyin** [oskarvid/wdl_pipeline#1]
Hi thanks for sharing this repo

Was just browsing your code and noticed that the 
interval files and germlinevarcall.json 
all mention the human_g1k_v37_decoy.fasta build

But b38 is mentioned in the README?

**Comment by oskarvid** [comment]
Hi, that's a valid point you're raising. I have added a file named germlinevarcall-hg38.json now, since I am on vacation I cannot test it at the moment, but I will make sure it runs as intended as soon as possible. Feel free to test it and let me know if it works if you want to.

**Comment by oskarvid** [comment]
I have now tested the changes and fixed the bugs that were present, as well as updated to gatk 4.0, everything works fine now.
